name: Docker Image CI

on:
 
  schedule:
  - cron: "0/5 * * * *"

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
      
    - name: run a multi script
      run: |
         echo Hello world!1
         echo Hello world!2
      
