name: Docker Image CI

on:
   schedule:
   - cron: "0 2 * * 1-5"

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: echo Hello, world!
#       docker build . --file Dockerfile --tag my-image-name:$(date +%s)
